"""Autogenerated TronClass API endpoint catalog discovered from the frontend bundle."""

TRONCLASS_API_GROUPS = {
  "academic-years": [
    {
      "url": "/api/academic-years?fields=id",
      "methods": []
    }
  ],
  "activies": [
    {
      "url": "/api/activies/classin/join-url",
      "methods": [
        "GET"
      ]
    }
  ],
  "activities": [
    {
      "url": "/api/activities",
      "methods": [
        "DELETE"
      ]
    },
    {
      "url": "/api/activities/",
      "methods": [
        "DELETE",
        "GET",
        "POST",
        "PUT"
      ]
    },
    {
      "url": "/api/activities/classin/webcast-url",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/activities/delete-check?activity_id=",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/activities/have-dependents",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/activities/resources/",
      "methods": [
        "POST"
      ]
    }
  ],
  "activity-resort": [
    {
      "url": "/api/activity-resort",
      "methods": [
        "PUT"
      ]
    }
  ],
  "activity": [
    {
      "url": "/api/activity/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/activity/cloud-classroom?start=",
      "methods": [
        "GET"
      ]
    }
  ],
  "ai-ppt": [
    {
      "url": "/api/ai-ppt/usage",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/ai-ppt/user/usage/count",
      "methods": [
        "GET"
      ]
    }
  ],
  "air-credit": [
    {
      "url": "/api/air-credit/audits",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/air-credit/course",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/air-credit/resources/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/air-credit/user",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/air-credit/user/courses/ai-ability",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/air-credit/user/token",
      "methods": [
        "GET"
      ]
    }
  ],
  "all-orgs": [
    {
      "url": "/api/all-orgs",
      "methods": []
    }
  ],
  "angular.element": [
    {
      "url": "/api/angular.element",
      "methods": []
    }
  ],
  "ask-questions": [
    {
      "url": "/api/ask-questions/",
      "methods": []
    }
  ],
  "auth_code": [
    {
      "url": "/api/auth_code/auth_validate",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/auth_code/get_auth_code",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/auth_code/validate_auth_code",
      "methods": [
        "POST"
      ]
    }
  ],
  "authz": [
    {
      "url": "/api/authz/course-roles",
      "methods": [
        "GET"
      ]
    }
  ],
  "blobstorage": [
    {
      "url": "/api/blobstorage/open-client-url?parent_id=",
      "methods": []
    }
  ],
  "blueprint": [
    {
      "url": "/api/blueprint/",
      "methods": [
        "GET"
      ]
    }
  ],
  "bulletins": [
    {
      "url": "/api/bulletins/",
      "methods": [
        "POST"
      ]
    }
  ],
  "calendar-alerts": [
    {
      "url": "/api/calendar-alerts?no-intercept=true",
      "methods": [
        "GET"
      ]
    }
  ],
  "calendar-events": [
    {
      "url": "/api/calendar-events",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/calendar-events/",
      "methods": [
        "DELETE",
        "PUT"
      ]
    },
    {
      "url": "/api/calendar-events/users/",
      "methods": []
    },
    {
      "url": "/api/calendar-events?no-intercept=true",
      "methods": [
        "GET"
      ]
    }
  ],
  "calendar-meeting": [
    {
      "url": "/api/calendar-meeting",
      "methods": [
        "GET",
        "POST"
      ]
    },
    {
      "url": "/api/calendar-meeting/",
      "methods": [
        "DELETE",
        "PUT"
      ]
    }
  ],
  "calendar-timetables": [
    {
      "url": "/api/calendar-timetables",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/calendar-timetables/",
      "methods": [
        "PUT"
      ]
    },
    {
      "url": "/api/calendar-timetables?no-intercept=true",
      "methods": [
        "GET"
      ]
    }
  ],
  "captures": [
    {
      "url": "/api/captures/",
      "methods": [
        "GET"
      ]
    }
  ],
  "cc-license": [
    {
      "url": "/api/cc-license/groups",
      "methods": []
    },
    {
      "url": "/api/cc-license/map",
      "methods": [
        "GET"
      ]
    }
  ],
  "certifications": [
    {
      "url": "/api/certifications",
      "methods": [
        "GET"
      ]
    }
  ],
  "chinamcloud": [
    {
      "url": "/api/chinamcloud/resources",
      "methods": []
    },
    {
      "url": "/api/chinamcloud/upload",
      "methods": [
        "POST"
      ]
    }
  ],
  "classes": [
    {
      "url": "/api/classes",
      "methods": []
    },
    {
      "url": "/api/classes?org_id=",
      "methods": []
    }
  ],
  "classrooms": [
    {
      "url": "/api/classrooms/",
      "methods": [
        "DELETE"
      ]
    }
  ],
  "combine-courses": [
    {
      "url": "/api/combine-courses",
      "methods": [
        "GET",
        "POST"
      ]
    },
    {
      "url": "/api/combine-courses/",
      "methods": [
        "GET",
        "POST"
      ]
    }
  ],
  "completion-criteria": [
    {
      "url": "/api/completion-criteria",
      "methods": [
        "GET"
      ]
    }
  ],
  "config": [
    {
      "url": "/api/config?no-intercept=true",
      "methods": [
        "GET"
      ]
    }
  ],
  "copy-third-part-resources": [
    {
      "url": "/api/copy-third-part-resources",
      "methods": [
        "POST"
      ]
    }
  ],
  "course": [
    {
      "url": "/api/course",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/course/",
      "methods": [
        "DELETE",
        "GET",
        "POST",
        "PUT"
      ]
    },
    {
      "url": "/api/course/access-code/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/course/activities-read/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/course/activities-read/exam/",
      "methods": []
    },
    {
      "url": "/api/course/activities/",
      "methods": [
        "GET",
        "PUT"
      ]
    },
    {
      "url": "/api/course/bulletins/",
      "methods": [
        "DELETE",
        "PUT"
      ]
    },
    {
      "url": "/api/course/custom-score-items/",
      "methods": [
        "DELETE",
        "PUT"
      ]
    },
    {
      "url": "/api/course/enrollments",
      "methods": [
        "DELETE",
        "PUT"
      ]
    },
    {
      "url": "/api/course/enrollments/",
      "methods": [
        "DELETE",
        "PUT"
      ]
    },
    {
      "url": "/api/course/mbz/import",
      "methods": [
        "POST"
      ]
    }
  ],
  "course-classifications": [
    {
      "url": "/api/course-classifications",
      "methods": [
        "GET"
      ]
    }
  ],
  "course-estimates": [
    {
      "url": "/api/course-estimates/",
      "methods": [
        "GET"
      ]
    }
  ],
  "courses": [
    {
      "url": "/api/courses/",
      "methods": [
        "DELETE",
        "GET",
        "POST",
        "PUT"
      ]
    },
    {
      "url": "/api/courses/count",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/courses/interactions/",
      "methods": [
        "PUT"
      ]
    },
    {
      "url": "/api/courses/interactions/vote/",
      "methods": [
        "PUT"
      ]
    },
    {
      "url": "/api/courses/lecture-live-activity/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/courses/settings",
      "methods": [
        "PUT"
      ]
    },
    {
      "url": "/api/courses/statistic/resource-audit",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/courses/sync_from_urp",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/courses/tencent-meeting/activities",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/courses/tpdoe/stat-students?",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/courses?page=",
      "methods": [
        "POST"
      ]
    }
  ],
  "courseware-quiz": [
    {
      "url": "/api/courseware-quiz/activity/",
      "methods": [
        "GET",
        "POST"
      ]
    },
    {
      "url": "/api/courseware-quiz/format-question",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/courseware-quiz/generate-subjects",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/courseware-quiz/generate-subjects-by-text",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/courseware-quiz/quiz/",
      "methods": [
        "GET",
        "POST",
        "PUT"
      ]
    },
    {
      "url": "/api/courseware-quiz/settings",
      "methods": [
        "GET"
      ]
    }
  ],
  "curriculum-classifications": [
    {
      "url": "/api/curriculum-classifications",
      "methods": [
        "GET"
      ]
    }
  ],
  "data-import": [
    {
      "url": "/api/data-import/chaoxing-score/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/course-groups",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/course/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/courses",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/edit-courses",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/enrollments",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/enrollments/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/from-word",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/item_scores/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/scores/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/seat-number/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/data-import/validation",
      "methods": [
        "POST"
      ]
    }
  ],
  "departments": [
    {
      "url": "/api/departments",
      "methods": []
    },
    {
      "url": "/api/departments/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/departments?",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/departments?no-intercept=true",
      "methods": [
        "GET"
      ]
    }
  ],
  "ding-talk": [
    {
      "url": "/api/ding-talk/chat?course_id=",
      "methods": [
        "GET",
        "PUT"
      ]
    },
    {
      "url": "/api/ding-talk/user-id",
      "methods": [
        "GET"
      ]
    }
  ],
  "dingtalk-lives": [
    {
      "url": "/api/dingtalk-lives/",
      "methods": []
    }
  ],
  "entries": [
    {
      "url": "/api/entries",
      "methods": [
        "GET"
      ]
    }
  ],
  "exam": [
    {
      "url": "/api/exam/",
      "methods": [
        "GET"
      ]
    }
  ],
  "exams": [
    {
      "url": "/api/exams/",
      "methods": [
        "DELETE",
        "POST"
      ]
    },
    {
      "url": "/api/exams/batch_delete",
      "methods": [
        "DELETE"
      ]
    }
  ],
  "grades": [
    {
      "url": "/api/grades",
      "methods": []
    },
    {
      "url": "/api/grades?org_id=",
      "methods": []
    }
  ],
  "grant": [
    {
      "url": "/api/grant/code/",
      "methods": []
    },
    {
      "url": "/api/grant/code?uid=",
      "methods": []
    }
  ],
  "group-sets": [
    {
      "url": "/api/group-sets/",
      "methods": [
        "DELETE",
        "GET",
        "POST",
        "PUT"
      ]
    }
  ],
  "groups": [
    {
      "url": "/api/groups/",
      "methods": [
        "DELETE",
        "PUT"
      ]
    }
  ],
  "h5-courseware": [
    {
      "url": "/api/h5-courseware/",
      "methods": []
    }
  ],
  "homework": [
    {
      "url": "/api/homework/",
      "methods": [
        "GET",
        "PUT"
      ]
    }
  ],
  "instruction-team": [
    {
      "url": "/api/instruction-team/meeting",
      "methods": [
        "GET"
      ]
    }
  ],
  "invites": [
    {
      "url": "/api/invites/",
      "methods": [
        "GET",
        "POST"
      ]
    }
  ],
  "knowledge-capture-visit": [
    {
      "url": "/api/knowledge-capture-visit",
      "methods": []
    }
  ],
  "knowledge-graph": [
    {
      "url": "/api/knowledge-graph/courses/",
      "methods": [
        "GET",
        "POST"
      ]
    },
    {
      "url": "/api/knowledge-graph/forest-versions/-/stats:batchGet",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/knowledge-graph/kfs-courses/-/published-forest-versions:batchGet",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/knowledge-graph/kfs-subjects",
      "methods": [
        "GET"
      ]
    }
  ],
  "knowledge-node": [
    {
      "url": "/api/knowledge-node/",
      "methods": [
        "DELETE",
        "GET",
        "POST",
        "PUT"
      ]
    }
  ],
  "knowledge-nodes": [
    {
      "url": "/api/knowledge-nodes/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/knowledge-nodes/parse/docx",
      "methods": [
        "POST"
      ]
    }
  ],
  "knowledge-resource-visit": [
    {
      "url": "/api/knowledge-resource-visit",
      "methods": []
    }
  ],
  "lark": [
    {
      "url": "/api/lark/authorization/check",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/lark/files",
      "methods": [
        "GET"
      ]
    }
  ],
  "lecture-live": [
    {
      "url": "/api/lecture-live/schedule/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/lecture-live?jwt=",
      "methods": []
    }
  ],
  "lesson-resources": [
    {
      "url": "/api/lesson-resources/shared-stat",
      "methods": [
        "GET"
      ]
    }
  ],
  "live-records": [
    {
      "url": "/api/live-records/",
      "methods": [
        "GET",
        "POST"
      ]
    }
  ],
  "management": [
    {
      "url": "/api/management/calendar-meeting/excel",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/management/calendar-meeting?page=",
      "methods": [
        "POST"
      ]
    }
  ],
  "meeting": [
    {
      "url": "/api/meeting/",
      "methods": []
    }
  ],
  "modules": [
    {
      "url": "/api/modules/",
      "methods": [
        "PUT"
      ]
    }
  ],
  "my-academic-years": [
    {
      "url": "/api/my-academic-years?fields=id",
      "methods": []
    }
  ],
  "my-captures": [
    {
      "url": "/api/my-captures",
      "methods": [
        "GET"
      ]
    }
  ],
  "my-courses": [
    {
      "url": "/api/my-courses",
      "methods": [
        "POST"
      ]
    }
  ],
  "my-curriculum-academic-years": [
    {
      "url": "/api/my-curriculum-academic-years?fields=id",
      "methods": []
    }
  ],
  "my-curriculum-semesters": [
    {
      "url": "/api/my-curriculum-semesters?",
      "methods": [
        "GET"
      ]
    }
  ],
  "my-semesters": [
    {
      "url": "/api/my-semesters",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/my-semesters?",
      "methods": [
        "GET"
      ]
    }
  ],
  "my-semesters-all": [
    {
      "url": "/api/my-semesters-all",
      "methods": []
    }
  ],
  "ng.": [
    {
      "url": "/api/ng.",
      "methods": []
    }
  ],
  "ngSanitize": [
    {
      "url": "/api/ngSanitize",
      "methods": []
    }
  ],
  "notes": [
    {
      "url": "/api/notes",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/notes/",
      "methods": [
        "DELETE",
        "PUT"
      ]
    },
    {
      "url": "/api/notes?course_id=",
      "methods": [
        "GET"
      ]
    }
  ],
  "obe": [
    {
      "url": "/api/obe/existed-metrics?params=",
      "methods": []
    }
  ],
  "online-videos": [
    {
      "url": "/api/online-videos/",
      "methods": [
        "GET"
      ]
    }
  ],
  "org": [
    {
      "url": "/api/org",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/org/",
      "methods": []
    }
  ],
  "org-bulletin": [
    {
      "url": "/api/org-bulletin/bulletins",
      "methods": [
        "GET",
        "POST"
      ]
    },
    {
      "url": "/api/org-bulletin/bulletins/",
      "methods": [
        "DELETE",
        "POST",
        "PUT"
      ]
    },
    {
      "url": "/api/org-bulletin/bulletins?fields=id",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/org-bulletin/classifications",
      "methods": [
        "GET"
      ]
    }
  ],
  "orgs": [
    {
      "url": "/api/orgs/",
      "methods": [
        "GET"
      ]
    }
  ],
  "outline": [
    {
      "url": "/api/outline/notify",
      "methods": [
        "POST"
      ]
    }
  ],
  "program": [
    {
      "url": "/api/program/course-programs?department_ids=",
      "methods": []
    },
    {
      "url": "/api/program/user-programs?fields=",
      "methods": []
    }
  ],
  "public-captures": [
    {
      "url": "/api/public-captures",
      "methods": [
        "GET"
      ]
    }
  ],
  "public-resources": [
    {
      "url": "/api/public-resources",
      "methods": []
    }
  ],
  "questionnaires": [
    {
      "url": "/api/questionnaires/",
      "methods": [
        "GET"
      ]
    }
  ],
  "resource-file": [
    {
      "url": "/api/resource-file/",
      "methods": []
    },
    {
      "url": "/api/resource-file/org/arrears/",
      "methods": [
        "GET"
      ]
    }
  ],
  "resource-group": [
    {
      "url": "/api/resource-group",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/resource-group/",
      "methods": [
        "DELETE",
        "PUT"
      ]
    }
  ],
  "resource-groups": [
    {
      "url": "/api/resource-groups",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/resource-groups/",
      "methods": [
        "DELETE",
        "GET",
        "POST",
        "PUT"
      ]
    },
    {
      "url": "/api/resource-groups/folders",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/resource-groups/resources",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/resource-groups?page=",
      "methods": [
        "POST"
      ]
    }
  ],
  "resources": [
    {
      "url": "/api/resources/",
      "methods": [
        "GET"
      ]
    }
  ],
  "rollcall": [
    {
      "url": "/api/rollcall/",
      "methods": []
    },
    {
      "url": "/api/rollcall/merged-rollcall",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/rollcall/merged-rollcall/student-rollcalls",
      "methods": [
        "PUT"
      ]
    }
  ],
  "semesters": [
    {
      "url": "/api/semesters",
      "methods": []
    }
  ],
  "shared-resource": [
    {
      "url": "/api/shared-resource/classifications",
      "methods": []
    }
  ],
  "shared-resources": [
    {
      "url": "/api/shared-resources/",
      "methods": [
        "DELETE"
      ]
    },
    {
      "url": "/api/shared-resources/management",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/shared-resources/stat",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/shared-resources/stat/video-resources",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/shared-resources/stat/video-resources/export",
      "methods": [
        "GET"
      ]
    }
  ],
  "slides": [
    {
      "url": "/api/slides?keyword=",
      "methods": [
        "GET"
      ]
    }
  ],
  "stat": [
    {
      "url": "/api/stat/activities-for-courses",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/stat/attendance/export/to/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/stat/courses/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/stat/courses/class-hours/export",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/stat/courses/export/to/",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/stat/courses/homework-correct/export",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/stat/courses/rollcall/export",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/stat/courses/rollcall/export-by-class",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/stat/vtrses/",
      "methods": [
        "GET"
      ]
    }
  ],
  "statistic": [
    {
      "url": "/api/statistic",
      "methods": []
    }
  ],
  "subject-libs": [
    {
      "url": "/api/subject-libs/",
      "methods": [
        "DELETE"
      ]
    }
  ],
  "submissions": [
    {
      "url": "/api/submissions/",
      "methods": [
        "GET",
        "POST"
      ]
    }
  ],
  "syllabus": [
    {
      "url": "/api/syllabus/",
      "methods": [
        "PUT"
      ]
    }
  ],
  "tencent_meeting": [
    {
      "url": "/api/tencent_meeting/check-user-auth",
      "methods": [
        "GET"
      ]
    }
  ],
  "toggle-opened-orgs": [
    {
      "url": "/api/toggle-opened-orgs?toggle=org_team_teaching",
      "methods": [
        "GET"
      ]
    }
  ],
  "top-departments": [
    {
      "url": "/api/top-departments?fields=",
      "methods": [
        "GET"
      ]
    }
  ],
  "uploads": [
    {
      "url": "/api/uploads",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/uploads/",
      "methods": [
        "DELETE",
        "GET",
        "POST",
        "PUT"
      ]
    },
    {
      "url": "/api/uploads/audio/",
      "methods": []
    },
    {
      "url": "/api/uploads/batch/blob",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/uploads/details/query",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/uploads/document/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/uploads/embed-material/",
      "methods": []
    },
    {
      "url": "/api/uploads/marked_attachment/",
      "methods": [
        "DELETE"
      ]
    },
    {
      "url": "/api/uploads/moodle-pkg?page=",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/uploads/reference/document/",
      "methods": []
    },
    {
      "url": "/api/uploads/references/",
      "methods": [
        "PUT"
      ]
    },
    {
      "url": "/api/uploads/scorm/",
      "methods": []
    },
    {
      "url": "/api/uploads/screen-shot",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/uploads/screen-shot/share-to",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/uploads/share-to-courses",
      "methods": [
        "POST"
      ]
    }
  ],
  "uptoken": [
    {
      "url": "/api/uptoken?id=",
      "methods": [
        "GET"
      ]
    }
  ],
  "user-actions": [
    {
      "url": "/api/user-actions?jwt=",
      "methods": []
    }
  ],
  "user-visits": [
    {
      "url": "/api/user-visits",
      "methods": []
    }
  ],
  "user": [
    {
      "url": "/api/user/academic-learning-resources",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/user/association-code",
      "methods": [
        "PUT"
      ]
    },
    {
      "url": "/api/user/chat",
      "methods": [
        "GET",
        "POST"
      ]
    },
    {
      "url": "/api/user/check-expired-password",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/user/classes",
      "methods": []
    },
    {
      "url": "/api/user/course-certification/scores",
      "methods": [
        "PUT"
      ]
    },
    {
      "url": "/api/user/course/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/user/language",
      "methods": [
        "PUT"
      ]
    },
    {
      "url": "/api/user/links",
      "methods": [
        "POST"
      ]
    },
    {
      "url": "/api/user/links/",
      "methods": [
        "PUT"
      ]
    },
    {
      "url": "/api/user/other-video-resources",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/user/pre-task",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/user/recently-visited-courses",
      "methods": [
        "GET",
        "PUT"
      ]
    },
    {
      "url": "/api/user/resources",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/user/search",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/user/send_org_sing_up_verification_email",
      "methods": []
    },
    {
      "url": "/api/user/send_verification_email",
      "methods": []
    },
    {
      "url": "/api/user/storage-used",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/user/third-part-resources",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/user?type=all&response_key=",
      "methods": []
    },
    {
      "url": "/api/user?type=instructor",
      "methods": []
    }
  ],
  "users": [
    {
      "url": "/api/users/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/users?page=",
      "methods": [
        "POST"
      ]
    }
  ],
  "video-quizzes": [
    {
      "url": "/api/video-quizzes/",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/video-quizzes/org/arrears/",
      "methods": [
        "GET"
      ]
    }
  ],
  "virtual-classroom-resources": [
    {
      "url": "/api/virtual-classroom-resources",
      "methods": [
        "GET",
        "POST"
      ]
    }
  ],
  "vtrses": [
    {
      "url": "/api/vtrses",
      "methods": [
        "GET"
      ]
    },
    {
      "url": "/api/vtrses/",
      "methods": [
        "DELETE",
        "GET",
        "POST",
        "PUT"
      ]
    },
    {
      "url": "/api/vtrses/resources/classifications/",
      "methods": [
        "DELETE",
        "GET",
        "PUT"
      ]
    },
    {
      "url": "/api/vtrses/share-resources",
      "methods": [
        "GET"
      ]
    }
  ],
  "warning": [
    {
      "url": "/api/warning/student/",
      "methods": [
        "PUT"
      ]
    }
  ],
  "wedrive": [
    {
      "url": "/api/wedrive/files?page=",
      "methods": []
    }
  ]
}

TRONCLASS_API_COUNT = 251
TRONCLASS_METHOD_COUNT = 204
